apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web-deployment
  labels:
    app: todo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec: 
      containers:
      - name: todo-web
        imagePullPolicy: Always
        image: <OCIR_REGION>/<REPOSITORY_NAME>/todo-web:latest
      imagePullSecrets:
      - name: ocirsecret
